Command renaming docs update

diff --git a/scripts/medaka_variant b/scripts/medaka_variant
--- a/scripts/medaka_variant
+++ b/scripts/medaka_variant
@@ -142,14 +142,14 @@ fi
 
 CONSENSUSPROBS=consensus_probs.hdf
 if [[ ! -e "${CONSENSUSPROBS}" ]] || ${FORCE}; then
-    echo "Running medaka consensus"
+    echo "Running medaka inference"
     rm -rf "${CONSENSUSPROBS}"
     medaka inference "${CALLS2REF}.bam" "${CONSENSUSPROBS}" \
         --model "${MODEL}" --batch_size "${BATCH_SIZE}" --threads "${THREADS}" \
-        || { echo "Failed to run medaka consensus."; exit 1; }
+        || { echo "Failed to run medaka inference."; exit 1; }
     FORCE=true
 else
-    echo "Not running medaka consensus, ${CONSENSUSPROBS} exists."
+    echo "Not running medaka inference, ${CONSENSUSPROBS} exists."
 fi
 
 VARIANTS=medaka.vcf
